Collections:
- Name: DEKR
  Paper:
    Title: Bottom-up human pose estimation via disentangled keypoint regression
    URL: https://arxiv.org/abs/2104.02300
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/dekr.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/disentangled_keypoint_regression/crowdpose/hrnet_w32_crowdpose_512x512.py
  In Collection: DEKR
  Metadata:
    Architecture: &id001
    - DEKR
    - HRNet
    Training Data: CrowdPose
  Name: disentangled_keypoint_regression_hrnet_w32_crowdpose_512x512
  Results:
  - Dataset: CrowdPose
    Metrics:
      AP: 0.663
      AP@0.5: 0.857
      AP@0.75: 0.715
      AR: 0.719
      AR@0.5: 0.893
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w32_crowdpose_512x512-685aff75_20220924.pth
- Config: configs/body/2d_kpt_sview_rgb_img/disentangled_keypoint_regression/crowdpose/hrnet_w48_crowdpose_640x640.py
  In Collection: DEKR
  Metadata:
    Architecture: *id001
    Training Data: CrowdPose
  Name: disentangled_keypoint_regression_hrnet_w48_crowdpose_640x640
  Results:
  - Dataset: CrowdPose
    Metrics:
      AP: 0.682
      AP@0.5: 0.869
      AP@0.75: 0.736
      AR: 0.742
      AR@0.5: 0.911
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w48_crowdpose_640x640-ef6b6040_20220930.pth
- Config: configs/body/2d_kpt_sview_rgb_img/disentangled_keypoint_regression/crowdpose/hrnet_w32_crowdpose_512x512_multiscale.py
  In Collection: DEKR
  Metadata:
    Architecture: *id001
    Training Data: CrowdPose
  Name: disentangled_keypoint_regression_hrnet_w32_crowdpose_512x512_multiscale
  Results:
  - Dataset: CrowdPose
    Metrics:
      AP: 0.692
      AP@0.5: 0.874
      AP@0.75: 0.748
      AR: 0.755
      AR@0.5: 0.926
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w32_crowdpose_512x512-685aff75_20220924.pth
- Config: configs/body/2d_kpt_sview_rgb_img/disentangled_keypoint_regression/crowdpose/hrnet_w48_crowdpose_640x640_multiscale.py
  In Collection: DEKR
  Metadata:
    Architecture: *id001
    Training Data: CrowdPose
  Name: disentangled_keypoint_regression_hrnet_w48_crowdpose_640x640_multiscale
  Results:
  - Dataset: CrowdPose
    Metrics:
      AP: 0.696
      AP@0.5: 0.869
      AP@0.75: 0.749
      AR: 0.769
      AR@0.5: 0.933
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w48_crowdpose_640x640-ef6b6040_20220930.pth
