Collections:
- Name: DEKR
  Paper:
    Title: Bottom-up human pose estimation via disentangled keypoint regression
    URL: https://arxiv.org/abs/2104.02300
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/dekr.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/disentangled_keypoint_regression/coco/hrnet_w32_coco_512x512.py
  In Collection: DEKR
  Metadata:
    Architecture: &id001
    - DEKR
    - HRNet
    Training Data: COCO
  Name: disentangled_keypoint_regression_hrnet_w32_coco_512x512
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.68
      AP@0.5: 0.868
      AP@0.75: 0.745
      AR: 0.728
      AR@0.5: 0.897
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w32_coco_512x512-2a3056de_20220928.pth
- Config: configs/body/2d_kpt_sview_rgb_img/disentangled_keypoint_regression/coco/hrnet_w48_coco_640x640.py
  In Collection: DEKR
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: disentangled_keypoint_regression_hrnet_w48_coco_640x640
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.709
      AP@0.5: 0.876
      AP@0.75: 0.773
      AR: 0.758
      AR@0.5: 0.909
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w48_coco_640x640-8854b2f1_20220930.pth
- Config: configs/body/2d_kpt_sview_rgb_img/disentangled_keypoint_regression/coco/hrnet_w32_coco_512x512_multiscale.py
  In Collection: DEKR
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: disentangled_keypoint_regression_hrnet_w32_coco_512x512_multiscale
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.705
      AP@0.5: 0.878
      AP@0.75: 0.767
      AR: 0.759
      AR@0.5: 0.921
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w32_coco_512x512-2a3056de_20220928.pth
- Config: configs/body/2d_kpt_sview_rgb_img/disentangled_keypoint_regression/coco/hrnet_w48_coco_640x640_multiscale.py
  In Collection: DEKR
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: disentangled_keypoint_regression_hrnet_w48_coco_640x640_multiscale
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.722
      AP@0.5: 0.882
      AP@0.75: 0.785
      AR: 0.778
      AR@0.5: 0.928
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/dekr/hrnet_w48_coco_640x640-8854b2f1_20220930.pth
