Collections:
- Name: PVT
  Paper:
    Title: 'Pyramid vision transformer: A versatile backbone for dense prediction
      without convolutions'
    URL: https://arxiv.org/abs/2102.12122
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/pvt.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/pvt-s_coco_256x192.py
  In Collection: PVT
  Metadata:
    Architecture: &id001
    - PVT
    Training Data: COCO
  Name: topdown_heatmap_pvt-s_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.714
      AP@0.5: 0.896
      AP@0.75: 0.794
      AR: 0.773
      AR@0.5: 0.936
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/pvt/pvt_small_coco_256x192-4324a49d_20220501.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/pvtv2-b2_coco_256x192.py
  In Collection: PVT
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_pvtv2-b2_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.737
      AP@0.5: 0.905
      AP@0.75: 0.812
      AR: 0.791
      AR@0.5: 0.942
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/pvt/pvtv2_b2_coco_256x192-b4212737_20220501.pth
