Collections:
- Name: VoxelPose
  Paper:
    Title: 'VoxelPose: Towards Multi-Camera 3D Human Pose Estimation in Wild Environment'
    URL: https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123460188.pdf
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/voxelpose.md
Models:
- Config: configs/body/3d_kpt_mview_rgb_img/voxelpose/shelf/voxelpose_prn32x32x32_cpn48x48x12_shelf_cam5.py
  In Collection: VoxelPose
  Metadata:
    Architecture: &id001
    - VoxelPose
    Training Data: Shelf
  Name: voxelpose_voxelpose_prn32x32x32_cpn48x48x12_shelf_cam5
  Results:
  - Dataset: Shelf
    Metrics: {}
    Task: Body 3D Keypoint
  Weights: https://download.openmmlab.com/mmpose/body3d/voxelpose/voxelpose_prn32x32x32_cpn48x48x12_shelf_cam5-24721ec7_20220323.pth
- Config: configs/body/3d_kpt_mview_rgb_img/voxelpose/shelf/voxelpose_prn64x64x64_cpn80x80x20_shelf_cam5.py
  In Collection: VoxelPose
  Metadata:
    Architecture: *id001
    Training Data: Shelf
  Name: voxelpose_voxelpose_prn64x64x64_cpn80x80x20_shelf_cam5
  Results:
  - Dataset: Shelf
    Metrics: {}
    Task: Body 3D Keypoint
  Weights: https://download.openmmlab.com/mmpose/body3d/voxelpose/voxelpose_prn64x64x64_cpn80x80x20_shelf_cam5-f406fefe_20220323.pth
